# ## regular init
left_ankle_pitch: 0.48
left_ankle_roll: 0.0
left_hip_pitch: -0.0
left_hip_roll: -0.148
left_hip_yaw: 0.0
left_knee: 0.0
right_ankle_pitch: -0.48
right_ankle_roll: -0.0
right_hip_pitch: 0.0
right_hip_roll: 0.148
right_hip_yaw: 0.0
right_knee: -0.0

# left_ankle_pitch: 0.48
# left_ankle_roll: 0.0
# left_hip_pitch: -0.33
# left_hip_roll: -0.0
# left_hip_yaw: 0.0
# left_knee: 0.05
# right_ankle_pitch: -0.48
# right_ankle_roll: -0.0
# right_hip_pitch: 0.33
# right_hip_roll: 0.0
# right_hip_yaw: 0.0
# right_knee: -0.05

#left_ankle_pitch: 0.0
#left_ankle_roll: 0.0
#left_hip_pitch: -0.3768
#left_hip_roll: -0.1582
#left_hip_yaw: 0.0
#left_knee: 0.8654
#right_ankle_pitch: -0.0
#right_ankle_roll: -0.0
#right_hip_pitch: 0.3768
#right_hip_roll: 0.1582
#right_hip_yaw: 0.0
#right_knee: -0.8654

# left_ankle_pitch: 0.0
# left_ankle_roll: 0.0
# left_hip_pitch: -0.0
# left_hip_roll: -0.0
# left_hip_yaw: 0.0
# left_knee: 0.0 #0.87266
# right_ankle_pitch: -0.0
# right_ankle_roll: -0.0
# right_hip_pitch: 0.0
# right_hip_roll: 0.0
# right_hip_yaw: 0.0
# right_knee: 0.0 #-0.87266
