#New 1.2.23: this is a modified copy of standing  - with are joint.
main:
  cycle_duration: 1.3
  actions_offset:
    right_shoulder_pitch: 0.0
    right_shoulder_roll: -0.15
    right_shoulder_yaw: 0.0
    right_elbow: -0.05
    right_wrist_motor_in: 0.5
    right_wrist_motor_out: 0.01
#    right_wrist_yew: 0.0
#    right_gripper: 0.0
  delta_actions_limit: {}
  emma: false
  lpf: false
  lpf_coeffs: false
  lpf_cutoff: 5
  assymetric_scaling: false
  assymetric_scaling_type: 1
  max_kp:
    right_shoulder_pitch: 200
    right_shoulder_roll: 200
    right_shoulder_yaw: 200
    right_elbow: 200
    right_wrist_motor_in: 50
#    right_wrist_motor_out: 50
#    right_wrist_yew: 200
#    right_gripper: 200
  max_kd:
    right_shoulder_pitch: 20
    right_shoulder_roll: 20
    right_shoulder_yaw: 20
    right_elbow: 20
    right_wrist_motor_in: 20
#    right_wrist_motor_out: 20
#    right_wrist_yew: 20
#    right_gripper: 20
  min_kp:
    right_shoulder_pitch: 5
    right_shoulder_roll: 5
    right_shoulder_yaw: 5
    right_elbow: 5
    right_wrist_motor_in: 5
#    right_wrist_motor_out: 5
#    right_wrist_yew: 5
#    right_gripper: 5
  min_kd:
    right_shoulder_pitch: 0.5
    right_shoulder_roll: 0.5
    right_shoulder_yaw: 0.5
    right_elbow: 0.5
    right_wrist_motor_in: 0.5
#    right_wrist_motor_out: 0.5
#    right_wrist_yew: 0.5
#    right_gripper: 0.5
  default_kp:
    shoulder_yaw: 50.0
    shoulder_roll: 50.0
    shoulder_pitch: 50.0
    elbow: 50.0
    wrist_pitch: 50.0
    wrist_roll: 50.0
#    wrist_yew: 50.0
  default_kd:
    shoulder_yaw: 5.0
    shoulder_roll: 5.0
    shoulder_pitch: 5.0
    elbow: 5.0
    wrist_pitch: 5.0
    wrist_roll: 5.0
#    wrist_yew: 5.0
  policy_update_step: 1
  amp_flag: true
  cls: PolicyTS
  name: standing
  visible_dofs:
  - right_shoulder_pitch
  - right_shoulder_roll
  - right_shoulder_yaw
  - right_elbow
  - right_wrist_motor_in
#  - right_wrist_motor_out
#  - right_wrist_yew
#  - right_gripper
  learned_pd: false
  aux_torque_output: false
  actions_activation: null
  pod_dof_dict:
    right_shoulder_pitch: 0
    right_shoulder_roll: 1
    right_shoulder_yaw: 2
    right_elbow: 3
    right_wrist_motor_in: 4
#    right_wrist_motor_out: 5
#    right_wrist_yew: 6
#    right_gripper: 7
  dof_pos_limits:
  - - -0.6100000143051147
    - 0.6100000143051147
  - - -0.2800000011920929
    - 0.2800000011920929
  - - -0.9200000166893005
    - 0.9200000166893005
  - - -0.8700000047683716
    - 0.8700000047683716
  - - -0.699999988079071
    - 0.699999988079071
#  - - -0.3499999940395355
#    - 0.3499999940395355
#  - - -0.6100000143051147
#    - 0.6100000143051147
#  - - -0.2800000011920929
#    - 0.2800000011920929
  soft_limit_factor: 1.0
  default_dof_pos:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
#  - 0.0
#  - 0.0
#  - 0.0
  model_path: /home/omri/code/ros2_workspace/menteebot/menteebot/e2e.ts
  torque_limits:
  - 30.0
  - 50.0
  - 50.0
  - 50.0
  - 50.0
#  - 10.0
#  - 30.0
#  - 50.0
  pd_gains:
    right_shoulder_pitch:
      kp: 50.0
      kd: 5.0
    right_shoulder_roll:
      kp: 50.0
      kd: 5.0
    right_shoulder_yaw:
      kp: 50.0
      kd: 5.0
    right_elbow:
      kp: 50.0
      kd: 5.0
    right_wrist_motor_in:
      kp: 50.0
      kd: 5.0
#    right_wrist_motor_out:
#      kp: 50.0
#      kd: 5.0
#    right_wrist_yew:
#      kp: 50.0
#      kd: 5.0
#    right_gripper:
#      kp: 50.0
#      kd: 5.0
  observations:
    visible_dof_pos:
      default_value:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
#      - 0.0
#      - 0.0
#      - 0.0
      function: get_visible_dof_pos
      obs_scale: 1.0
      noise_scale_mul:
      - 1.0
      - 1.0
      noise_scale_add:
      - 0.0
      - 0.0
      size: 5
    visible_dof_vel:
      default_value:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
#      - 0.0
#      - 0.0
#      - 0.0
      function: get_visible_dof_vel
      obs_scale: 1.0
      noise_scale_mul:
      - 1.0
      - 1.0
      noise_scale_add:
      - 0.0
      - 0.0
      size: 5
#    get_imu_quat:
#      default_value:
#      - 0.0
#      - 0.0
#      - 0.0
#      - 0.0
#      function: get_imu_quat
#      obs_scale: 1.0
#      noise_scale_mul:
#      - 1.0
#      - 1.0
#      noise_scale_add:
#      - 0.0
#      - 0.0
#      size: 4
#    get_imu_ang_v_local:
#      default_value:
#      - 0.0
#      - 0.0
#      - 0.0
#      function: get_imu_ang_v_local
#      obs_scale: 1.0
#      noise_scale_mul:
#      - 1.0
#      - 1.0
#      noise_scale_add:
#      - 0.0
#      - 0.0
#      size: 3
#    get_lin_acc_local:
#      default_value:
#      - 0.0
#      - 0.0
#      - 0.0
#      function: get_lin_acc_local
#      obs_scale: 1.0
#      noise_scale_mul:
#      - 1.0
#      - 1.0
#      noise_scale_add:
#      - 0.0
#      - 0.0
#      size: 3
#    temporal_encoding:
#      default_value:
#      - 0.0
#      - 0.0
#      function: temporal_encoding
#      obs_scale: 1.0
#      noise_scale_mul:
#      - 1.0
#      - 1.0
#      noise_scale_add:
#      - 0.0
#      - 0.0
#      update_freq: 250
#      delay: 0.0
#      max_delay: 0.02
#      size: 2
#    heading:
#      default_value:
#      - 0.0
#      function: get_heading
#      obs_scale: 1.0
#      noise_scale_mul:
#      - 1.0
#      - 1.0
#      noise_scale_add:
#      - 0.0
#      - 0.0
#      size: 1
#    command:
#      default_value:
#      - 0.0
#      - 0.0
#      - 0.0
#      - 0.02
#      function: get_commands
#      obs_scale: 1.0
#      noise_scale_mul:
#      - 1.0
#      - 1.0
#      noise_scale_add:
#      - 0.0
#      - 0.0
#      size: 1
#      params:
#        end: 4
#  command_dict:
#    default_value:
#      lin_vel_x: 0.0
#      lin_vel_y: 0.0
#      heading: 0.0
#      foot_height: 0.02
#    ranges:
#      lin_vel_x:
#      - -0.25
#      - 0.25
#      lin_vel_y:
#      - -0.2
#      - 0.2
#      heading:
#      - -3.14
#      - 3.14
#      foot_height:
#      - -0.02
#      - 0.12
#    increment:
#      lin_vel_x: 0.05
#      lin_vel_y: 0.05
#      heading: 0.05
#      foot_height: 0.01
#    key_map:
#      lin_vel_x:
#      - w
#      - s
#      lin_vel_y:
#      - q
#      - e
#      heading:
#      - a
#      - d
#      foot_height:
#      - u
#      - j
  model_trace_path: /home/robot/code/ros2_workspace/menteebot/menteebot/e2e.ts
  #/home/tom/experiments/tom/run/play/play/experiment_922/e2e.ts