main:
  cls: SetActionSeries
  name: set_actions
  loop_back: false
  read_colum: true
#  ./run-menteebot-with-cleanup -e '/home/robot/Documents/Motion/Wrist_Exp_Adi/right_wrist_yaw_sine.csv' -f 30 -p -n
#  experiment_file: /home/robot/Documents/Motion/Wrist_Exp_Adi/right_wrist_pitch_sine.csv
  experiment_file: /home/robot/Documents/Motion/Wrist_Exp_Adi/right_wrist_yaw_sine.csv

  candle_params:
    baudrate: 1M
    bus_type: USB
  visible_dofs:
    - right_shoulder_pitch
    - right_shoulder_roll
    - right_shoulder_yaw
    - right_elbow
    - right_wrist_yaw
    - right_wrist_pitch
    - right_wrist_roll
  default_dof_pos:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  observations:
    visible_delta_dof:
      default_value:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      function: get_visible_dof_pos
      obs_scale: 4.0
      noise_scale_mul:
        - 1.0
        - 1.0
      noise_scale_add:
        - -0.0
        - 0.0
      update_freq: 200
      delay: 0.0
      max_delay: 0.02
      size: 10
    visible_dof_vel:
      default_value:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      function: get_visible_dof_vel
      obs_scale: 1.0
      noise_scale_mul:
        - 1.0
        - 1.0
      noise_scale_add:
        - -0.0
        - 0.0
      update_freq: 200
      delay: 0.0
      max_delay: 0.02
      size: 10
