100: left_hip_yaw
101: left_hip_roll
102: left_hip_pitch
103: left_knee
104: left_ankle_pitch
105: left_ankle_roll
106: right_hip_yaw
107: right_hip_roll
108: right_hip_pitch
109: right_knee
110: right_ankle_pitch
111: right_ankle_roll
