300: right_quad_in
301: right_quad_out
302: right_hamstring

######################################################################
######################################################################

#NEW 27.3.23: was added for new MenteeLeg experimental setup