defaults:
  - motors: ["upper_body_motor_no_ros_realT_joy"]
#  - imus: ["sim_imu"]             #value!
#  # - distances: ["default"]        #value!
  - teleops: ["default"]          #value!
#  - contact: ["default"]          #value!
