# New 31.1.23: this is a modiferd version of:
# state no ros
dofs:
  cls: DofStateManagerNoROS
  motors: ${...sensors.motors}

#rigid_bodies:
#  cls: RigidBodyStateManager
#  imus: ${...sensors.imus}
#
##distance:
##  cls: DistanceStateManager
##  sensors: ${...sensors.distances}
#
##New 31.1.23: Ask Sapir what is the diffrence
#

command:
  cls: CommandStateHandler
  command: ${...sensors.teleops}
joy_command:
  cls: JoystickCommandStateHandler
  command: ${...sensors.teleops}

#contact:
#  cls: ContactStateManager
#  sensors: ${...sensors.contact}
